name: flutter_project
description: Demo flutter project - login, calling API, showing list and details on that list.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  http: ^0.13.5
  mockito: ^5.3.2
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4+2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:
  uses-material-design: true